# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


	config.vm.box = "debian-7.6"
	config.vm.box_url = "https://github.com/jose-lpa/packer-debian_7.6.0/releases/download/1.0/packer_virtualbox-iso_virtualbox.box"
	config.vm.box_check_update = false


	config.vm.synced_folder "../../../", "/git", type: "virtualbox"
	
	#config.vm.network "public_network",use_dhcp_assigned_default_route: true
	config.vm.network "forwarded_port", guest: 27017, host: 27017, auto_correct: true				# mongodb
	
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
	end
	
	config.vm.provision :shell do |shell|
		shell.inline = "sudo echo export PATH=\"'/home/vagrant/.rbenv/shims/:$PATH'\" >> /root/.bashrc"
	end

	config.vm.provision "chef_solo" do |chef|

		chef.cookbooks_path = ["../../chef/cookbooks"]
		chef.roles_path = ["../chef/roles"]
		chef.add_role "vagrant-test-box"
		install = false
	end


end
