default['domusguard']['src_filepath'] =  '/git'
default['domusguard']['user'] =  'domus'
default['domusguard']['pwd'] =  '#SECRET#'
default['domusguard']['group'] =  'domus'
default['domusguard']['install_directory']  = '/opt/domus'
default['domusguard']['dbuser'] =  'domus'
default['domusguard']['dbpwd'] =  '#SECRET#'
default['domusguard']['cert']['common_name'] =  '#WEB_CERT_CN#'
default['domusguard']['cert']['contry'] =  '#WEB_CERT_COUNTRY#'
default['domusguard']['cert']['city'] =  '#WEB_CERT_CITY#'
default['domusguard']['web']['url'] =  '#URL#'
default['domusguard']['web']['google']['clientID'] =  '#GOOGLE_CLIENT_ID#'
default['domusguard']['web']['google']['clientSecret'] =  '#GOOGLE_CLIENT_SECRET#'
default['domusguard']['web']['google']['callbackURL'] =  '#GOOGLE_CLIENT_CALLBACK_URL#'
default['domusguard']['web']['google']['gcm'] =  '#GOOGLE_CLIENT_GCM#'

